USE [master]
GO

/****** Object:  Database [Skjatexti]    Script Date: 8.5.2014 08:49:12 ******/
CREATE DATABASE [Skjatexti]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Skjatexti', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Skjatexti.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Skjatexti_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Skjatexti_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Skjatexti] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Skjatexti].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Skjatexti] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Skjatexti] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Skjatexti] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Skjatexti] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Skjatexti] SET ARITHABORT OFF 
GO

ALTER DATABASE [Skjatexti] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Skjatexti] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Skjatexti] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Skjatexti] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Skjatexti] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Skjatexti] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Skjatexti] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Skjatexti] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Skjatexti] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Skjatexti] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Skjatexti] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Skjatexti] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Skjatexti] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Skjatexti] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Skjatexti] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Skjatexti] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Skjatexti] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Skjatexti] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Skjatexti] SET RECOVERY FULL 
GO

ALTER DATABASE [Skjatexti] SET  MULTI_USER 
GO

ALTER DATABASE [Skjatexti] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Skjatexti] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Skjatexti] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Skjatexti] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Skjatexti] SET  READ_WRITE 
GO

