//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skjatextar
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentCollection
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public int commentId { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> commentDate { get; set; }
        public int strId { get; set; }
        public string AspNetUsersId { get; set; }
        public int srtId { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> srtDate { get; set; }
        public Nullable<int> srtCounter { get; set; }
        public Nullable<int> movieId { get; set; }
        public Nullable<int> tvId { get; set; }
        public Nullable<int> dataId { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> dataSize { get; set; }
        public int Expr1 { get; set; }
        public string dataName { get; set; }
        public string dataText { get; set; }
    }
}
