//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skjatextar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.SrtFile = new HashSet<SrtFile>();
        }
    
        public int movieId { get; set; }
        public int year { get; set; }
    
        public virtual ICollection<SrtFile> SrtFile { get; set; }
    }
}
