//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skjatextar
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrtCollection
    {
        public int srtId { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> srtDate { get; set; }
        public Nullable<int> srtReady { get; set; }
        public Nullable<System.DateTime> rdDate { get; set; }
        public Nullable<int> srtCounter { get; set; }
        public Nullable<int> srtLike { get; set; }
        public Nullable<int> movieId { get; set; }
        public Nullable<int> tvId { get; set; }
        public Nullable<int> Expr4 { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> episode { get; set; }
        public Nullable<int> season { get; set; }
        public string episodeTitle { get; set; }
        public string episodeAbout { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> type { get; set; }
        public int Expr3 { get; set; }
        public Nullable<int> dataSize { get; set; }
        public string dataText { get; set; }
        public string dataName { get; set; }
    }
}
