//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skjatextar
{
    using System;
    using System.Collections.Generic;
    
    public partial class TvShow
    {
        public int tvId { get; set; }
        public string Episode { get; set; }
        public string Season { get; set; }
        public string EpisodeTitle { get; set; }
        public string EpisodeAbout { get; set; }
    }
}
