//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skjatextar
{
    using System;
    using System.Collections.Generic;
    
    public partial class TvShow
    {
        public TvShow()
        {
            this.SrtFile = new HashSet<SrtFile>();
        }
    
        public int tvId { get; set; }
        public int episode { get; set; }
        public int season { get; set; }
        public string episodeTitle { get; set; }
        public string episodeAbout { get; set; }
    
        public virtual ICollection<SrtFile> SrtFile { get; set; }
    }
}
